import type { DemoCall } from "./types";

export const DEMO_CALLS: DemoCall[] = [
  {
    id: "pricing-too-early",
    name: "Pricing Too Early (Risk Spike)",
    description:
      "Rep jumps into pricing before value is anchored. Buyer pushes back, momentum drops, rep recovers late.",
    durationSec: 240,
    outcome: "Pipeline",
    chunks: [
      { t: 4, speaker: "REP", text: "Thanks for taking the time. What prompted you to look at this now?" },
      { t: 10, speaker: "BUYER", text: "We need to improve rep productivity. We lose time on admin work and coaching is inconsistent." },
      { t: 18, speaker: "REP", text: "Got it. How are you coaching today—call reviews, scorecards, something else?" },
      { t: 28, speaker: "BUYER", text: "Mostly call recordings and weekly reviews. It’s too late by then." },
      { t: 38, speaker: "REP", text: "Makes sense. How many reps are you supporting and what tools are in the stack?" },
      { t: 52, speaker: "BUYER", text: "Around 18 reps. We use HubSpot, Gong, and Slack." },
      { t: 66, speaker: "REP", text: "Okay. We can help. Before we go deep, what’s your budget range for something like this?" },
      { t: 78, speaker: "BUYER", text: "We don’t know yet. We’re evaluating options. Why do you ask already?" },
      { t: 92, speaker: "REP", text: "Just to ensure we’re aligned. Our pricing typically depends on seats and features." },
      { t: 105, speaker: "BUYER", text: "We’re not ready for pricing. What’s the actual value here compared to Gong?" },
      { t: 118, speaker: "REP", text: "Fair. Gong is great at analysis. We focus on real-time correction and coaching attribution." },
      { t: 135, speaker: "BUYER", text: "Real-time? During the call? That’s interesting. But how accurate is it?" },
      { t: 150, speaker: "REP", text: "We use signal detection like objection density, talk-time, pricing pressure cues—then nudge at the right moment." },
      { t: 168, speaker: "BUYER", text: "If it’s wrong, reps will hate it. They hate clutter." },
      { t: 182, speaker: "REP", text: "Totally. UI is minimal: a health strip and occasional one-line nudges. No walls of text." },
      { t: 198, speaker: "BUYER", text: "Okay. What does implementation look like? Zoom? Meet? Teams?" },
      { t: 210, speaker: "REP", text: "Zoom first, then Teams. We can start with transcript ingestion and expand to audio streaming." },
      { t: 226, speaker: "BUYER", text: "Send a short summary and a couple customer examples if you have them." },
      { t: 236, speaker: "REP", text: "Will do. Next step: a quick pilot with 3 reps to measure before/after." },
    ],
  },
  {
    id: "no-decision-maker",
    name: "No Decision Maker (Hidden Blocker)",
    description:
      "Buyer sounds interested but no authority. Rep fails to confirm decision process early, deal stalls.",
    durationSec: 230,
    outcome: "Lost",
    chunks: [
      { t: 6, speaker: "REP", text: "What would make this a win for you in the next month?" },
      { t: 12, speaker: "BUYER", text: "If reps improved objection handling and we reduced ramp time." },
      { t: 22, speaker: "REP", text: "Great. What’s the biggest friction point right now—discovery, pricing, or closing?" },
      { t: 34, speaker: "BUYER", text: "Discovery. Reps talk too much and miss signals." },
      { t: 48, speaker: "REP", text: "We can fix that with live talk-time and question prompts." },
      { t: 60, speaker: "BUYER", text: "That sounds good. We need something like this." },
      { t: 76, speaker: "REP", text: "Awesome. Would you be able to move forward this quarter?" },
      { t: 86, speaker: "BUYER", text: "Maybe. I’ll need to run it by my VP and IT security." },
      { t: 98, speaker: "REP", text: "Okay. What does your decision process usually look like?" },
      { t: 110, speaker: "BUYER", text: "Not sure. IT can take weeks. The VP is busy." },
      { t: 126, speaker: "REP", text: "Got it. We can send materials. Pricing is per seat." },
      { t: 140, speaker: "BUYER", text: "I can’t commit to anything. Just send info." },
      { t: 156, speaker: "REP", text: "Understood. Could we schedule 15 minutes with your VP for alignment?" },
      { t: 170, speaker: "BUYER", text: "I’ll try. No promises." },
      { t: 198, speaker: "REP", text: "Okay—sending a short recap and suggested pilot plan." },
    ],
  },
  {
    id: "strong-discovery",
    name: "Strong Discovery (Clean Win)",
    description:
      "Rep stays in discovery, confirms decision process, handles objections calmly. Signals stay green.",
    durationSec: 220,
    outcome: "Won",
    chunks: [
      { t: 5, speaker: "REP", text: "What changed recently that made this a priority now?" },
      { t: 12, speaker: "BUYER", text: "We’re scaling the team. Coaching doesn’t scale. We need consistent improvement." },
      { t: 24, speaker: "REP", text: "Makes sense. What does ‘consistent improvement’ mean—shorter ramp, higher close rate, fewer stalled deals?" },
      { t: 36, speaker: "BUYER", text: "All three. Especially stalled deals." },
      { t: 48, speaker: "REP", text: "What’s the top reason deals stall today? Pricing, timing, lack of champion, or unclear value?" },
      { t: 64, speaker: "BUYER", text: "Timing and unclear value. Reps miss buying signals." },
      { t: 78, speaker: "REP", text: "If we can detect those signals live and nudge reps at the exact moment, would that be worth piloting?" },
      { t: 92, speaker: "BUYER", text: "Yes. During the call is when it matters." },
      { t: 106, speaker: "REP", text: "Great. Who besides you needs to approve a pilot?" },
      { t: 118, speaker: "BUYER", text: "My VP and RevOps. IT will review security." },
      { t: 132, speaker: "REP", text: "Perfect. Let’s include RevOps early. Any security constraints I should anticipate?" },
      { t: 148, speaker: "BUYER", text: "We prefer transcript-only first, then audio later." },
      { t: 162, speaker: "REP", text: "That’s exactly how we roll out: transcript ingestion first, then optional audio for higher fidelity." },
      { t: 186, speaker: "BUYER", text: "Sounds good. Let’s do a pilot with three reps next week." },
      { t: 206, speaker: "REP", text: "Done. I’ll send a one-pager and proposed success metrics today." },
    ],
  },
];
